services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - # Network name of choice 

  app:
    image: my-app
    ports:
      - # Port of choice
    environment:
      MYSQL_HOST: mysql # Name of the mysql container
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: 
    depends_on:
      - mysql # Name of the mysql container
    networks:
      - # Network name of choice 

networks:
  network-example: # Network name of choice 

volumes:
  mysql_data:
